[General]
network = Aloha

sim-time-limit = 120s

Aloha.N = 10 # number of stations
Aloha.C = 10000Bps # channel capacity
Aloha.station[*].S = 1000B # size of messages (bytes)
Aloha.station[*].W = 0.2s # acknowledgement wait time (2*D)
Aloha.slotTime = 0s # no slots -> Pure ALOHA

**.x = uniform(0m, 1000m)
**.y = uniform(0m, 1000m)
**.animationHoldTimeOnCollision = 0s
**.idleAnimationSpeed = 1
**.transmissionEdgeAnimationSpeed = 1e-6
**.midTransmissionAnimationSpeed = 1e-1

[Experiment_varyN]
description = "fixed T, various values of N"
repeat = 1
Aloha.N = ${N=5,10,15,20,25,30} # vary N
Aloha.station[*].T = exponential(6s) # fix T (optimal)

[Experiment_varyT]
description = "fixed N, various exponential mean values of T"
repeat = 1
Aloha.N = 10 # fix N
Aloha.station[*].T = exponential(${T=2,6,30}s) # vary T (overload, optimal, low traffic)

[Experiment_varyN_T]
description = "various values of N, various exponential mean values of T"
repeat = 1
seed-set = 20
Aloha.N = ${N=5,10,15,20,25,30} # vary N
Aloha.station[*].T = exponential(${T=2,4,6..30 step 2}s) # vary T (overload, optimal, low traffic)

[PureAloha1]
description = "pure Aloha, overloaded"
# too frequent transmissions result in high collision rate and low channel utilization
Aloha.station[*].T = exponential(2s)

[PureAloha2]
description = "pure Aloha, optimal load"
# near optimal load, channel utilization is near theoretical maximum 1/2e
Aloha.station[*].T = exponential(6s)

[PureAloha3]
description = "pure Aloha, low traffic"
# very low traffic results in channel being idle most of the time
Aloha.station[*].T = exponential(30s)

[PureAlohaExperiment]
description = "Channel utilization in the function of packet generation frequency"
repeat = 2
sim-time-limit = 90min
#**.vector-recording = false
Aloha.N = ${N=10,15,20}
Aloha.station[*].T = exponential(${iaMean=1,2,3,4,5..9 step 2}s)

[SlottedAloha1]
description = "slotted Aloha, overloaded"
# slotTime = S/C = 960/9600 = 0.1s
Aloha.slotTime = 100ms
# too frequent transmissions result in high collision rate and low channel utilization
Aloha.station[*].T = exponential(0.5s)

[SlottedAloha2]
description = "slotted Aloha, optimal load"
# slotTime = S/C = 960/9600 = 0.1s
Aloha.slotTime = 100ms
# near optimal load, channel utilization is near theoretical maximum 1/e
Aloha.station[*].T = exponential(2s)

[SlottedAloha3]
description = "slotted Aloha, low traffic"
# slotTime = S/C = 960/9600 = 0.1s
Aloha.slotTime = 100ms
# very low traffic results in channel being idle most of the time
Aloha.station[*].T = exponential(20s)